name: Deploy Hugo Site

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # Or specify a version
          extended: true # Set to true if you use Hugo extended

      - name: Build website
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/github-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: reika.io # Optional: Add your custom domain
